#!/usr/bin/env python

# Copyright 2024 Columbia Artificial Intelligence, Robotics Lab,
# and The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Diffusion Policy as per "Diffusion Policy: Visuomotor Policy Learning via Action Diffusion"

TODO(alexander-soare):
  - Remove reliance on diffusers for DDPMScheduler and LR scheduler.
"""

from asyncio import Condition
import math
from collections import deque
from collections.abc import Callable

import einops
import numpy as np
import torch
import torch.nn.functional as F  # noqa: N812
import torchvision
from diffusers.schedulers.scheduling_ddim import DDIMScheduler
from diffusers.schedulers.scheduling_ddpm import DDPMScheduler
from torch import Tensor, nn

from lerobot.policies.diffusion.configuration_diffusion import DiffusionConfig
from lerobot.policies.pretrained import PreTrainedPolicy
from lerobot.policies.utils import (
    get_device_from_parameters,
    get_dtype_from_parameters,
    get_output_shape,
    populate_queues,
)
from lerobot.utils.constants import ACTION, OBS_ENV_STATE, OBS_IMAGES, OBS_STATE


class DiffusionPolicy(PreTrainedPolicy):
    """
    Diffusion Policy as per "Diffusion Policy: Visuomotor Policy Learning via Action Diffusion"
    (paper: https://huggingface.co/papers/2303.04137, code: https://github.com/real-stanford/diffusion_policy).
    """

    config_class = DiffusionConfig
    name = "diffusion"

    def __init__(
        self,
        config: DiffusionConfig,
    ):
        """
        Args:
            config: Policy configuration class instance or None, in which case the default instantiation of
                the configuration class is used.
            dataset_stats: Dataset statistics to be used for normalization. If not passed here, it is expected
                that they will be passed with a call to `load_state_dict` before the policy is used.
        """
        super().__init__(config)
        config.validate_features()
        self.config = config

        # queues are populated during rollout of the policy, they contain the n latest observations and actions
        self._queues = None

        if config.diffusion_type == "diffusion":
            self.diffusion = DiffusionModel(config)
        elif config.diffusion_type == "flow":
            self.diffusion = FlowModel(config)
        else:
            raise ValueError(f"Unsupported diffusion type {config.diffusion_type}")

        self.reset()

    def get_optim_params(self) -> dict:
        return self.diffusion.parameters()

    def reset(self):
        """Clear observation and action queues. Should be called on `env.reset()`"""
        self._queues = {
            OBS_STATE: deque(maxlen=self.config.n_obs_steps),
            ACTION: deque(maxlen=self.config.n_action_steps),
        }
        if self.config.image_features:
            self._queues[OBS_IMAGES] = deque(maxlen=self.config.n_obs_steps)
        if self.config.env_state_feature:
            self._queues[OBS_ENV_STATE] = deque(maxlen=self.config.n_obs_steps)

    @torch.no_grad()
    def predict_action_chunk(self, batch: dict[str, Tensor], noise: Tensor | None = None, full_length: bool = False, action_cond=None) -> Tensor:
        """Predict a chunk of actions given environment observations."""
        # stack n latest observations from the queue
        batch = {k: torch.stack(list(self._queues[k]), dim=1) for k in batch if k in self._queues}
        actions = self.diffusion.generate_actions(batch, noise=noise, full_length=full_length, action_cond=action_cond)

        return actions

    @torch.no_grad()
    def select_action(self, batch: dict[str, Tensor], noise: Tensor | None = None) -> Tensor:
        """Select a single action given environment observations.

        This method handles caching a history of observations and an action trajectory generated by the
        underlying diffusion model. Here's how it works:
          - `n_obs_steps` steps worth of observations are cached (for the first steps, the observation is
            copied `n_obs_steps` times to fill the cache).
          - The diffusion model generates `horizon` steps worth of actions.
          - `n_action_steps` worth of actions are actually kept for execution, starting from the current step.
        Schematically this looks like:
            ----------------------------------------------------------------------------------------------
            (legend: o = n_obs_steps, h = horizon, a = n_action_steps)
            |timestep            | n-o+1 | n-o+2 | ..... | n     | ..... | n+a-1 | n+a   | ..... | n-o+h |
            |observation is used | YES   | YES   | YES   | YES   | NO    | NO    | NO    | NO    | NO    |
            |action is generated | YES   | YES   | YES   | YES   | YES   | YES   | YES   | YES   | YES   |
            |action is used      | NO    | NO    | NO    | YES   | YES   | YES   | NO    | NO    | NO    |
            ----------------------------------------------------------------------------------------------
        Note that this means we require: `n_action_steps <= horizon - n_obs_steps + 1`. Also, note that
        "horizon" may not the best name to describe what the variable actually means, because this period is
        actually measured from the first observation which (if `n_obs_steps` > 1) happened in the past.
        """
        # NOTE: for offline evaluation, we have action in the batch, so we need to pop it out
        if ACTION in batch:
            batch.pop(ACTION)

        if self.config.image_features:
            batch = dict(batch)  # shallow copy so that adding a key doesn't modify the original
            batch[OBS_IMAGES] = torch.stack([batch[key] for key in self.config.image_features], dim=-4)
        # NOTE: It's important that this happens after stacking the images into a single key.
        self._queues = populate_queues(self._queues, batch)

        if len(self._queues[ACTION]) == 0:
            actions = self.predict_action_chunk(batch, noise=noise)
            self._queues[ACTION].extend(actions.transpose(0, 1))

        action = self._queues[ACTION].popleft()
        return action

    def forward(self, batch: dict[str, Tensor]) -> tuple[Tensor, None]:
        """Run the batch through the model and compute the loss for training or validation."""
        if self.config.image_features:
            batch = dict(batch)  # shallow copy so that adding a key doesn't modify the original
            batch[OBS_IMAGES] = torch.stack([batch[key] for key in self.config.image_features], dim=-4)
        loss = self.diffusion.compute_loss(batch)
        # no output_dict so returning None
        return loss, None

    def critic_forward(self, batch: dict[str, Tensor]) -> tuple[Tensor, None]:
        """Run the critic on a batch with 'ret' targets and return the MSE loss."""
        if self.config.image_features:
            batch = dict(batch)
            batch[OBS_IMAGES] = torch.stack([batch[key] for key in self.config.image_features], dim=-4)
        loss = self.diffusion.critic_loss(batch)
        return loss, None


def _make_noise_scheduler(name: str, **kwargs: dict) -> DDPMScheduler | DDIMScheduler:
    """
    Factory for noise scheduler instances of the requested type. All kwargs are passed
    to the scheduler.
    """
    if name == "DDPM":
        return DDPMScheduler(**kwargs)
    elif name == "DDIM":
        return DDIMScheduler(**kwargs)
    else:
        raise ValueError(f"Unsupported noise scheduler type {name}")


class DiffusionCritic(nn.Module):
    """Value function: global_cond → scalar return estimate."""

    def __init__(self, obs_dim: int, hidden_dims: tuple[int, ...]):
        super().__init__()
        layers = []
        in_dim = obs_dim
        for h in hidden_dims:
            layers += [nn.Linear(in_dim, h), nn.ReLU()]
            in_dim = h
        layers.append(nn.Linear(in_dim, 1))
        self.net = nn.Sequential(*layers)

    def forward(self, global_cond: Tensor) -> Tensor:
        return self.net(global_cond)  # (B, 1)


class DiffusionModel(nn.Module):
    def __init__(self, config: DiffusionConfig):
        super().__init__()
        self.config = config

        # Build observation encoders (depending on which observations are provided).
        use_dit = config.use_dit
        global_cond_dim = self.config.robot_state_feature.shape[0]
        if self.config.image_features:
            num_images = len(self.config.image_features)
            if use_dit:
                if self.config.vision_backbone.startswith("resnet") or self.config.vision_backbone == "small_vit":
                    raise ValueError("DiT option requires DinoV3 vision backbone (e.g. dinov3_vits16plus).")
                self.rgb_encoder = DiffusionDinoV3Encoder(config)
                global_cond_dim += self.rgb_encoder.feature_dim * num_images
            elif self.config.vision_backbone.startswith("resnet"):
                if self.config.use_separate_rgb_encoder_per_camera:
                    encoders = [DiffusionRgbEncoder(config) for _ in range(num_images)]
                    self.rgb_encoder = nn.ModuleList(encoders)
                    global_cond_dim += encoders[0].feature_dim * num_images
                else:
                    self.rgb_encoder = DiffusionRgbEncoder(config)
                    global_cond_dim += self.rgb_encoder.feature_dim * num_images
            elif self.config.vision_backbone == "small_vit":
                encoders = [
                    DiffusionSmallVitEncoder(config)
                    for _ in range(num_images)
                ]
                self.rgb_encoder = nn.ModuleList(encoders)
                global_cond_dim += sum(encoder.feature_dim for encoder in encoders)
            else:
                self.rgb_encoder = DiffusionDinoV3Encoder(config)
                global_cond_dim += self.rgb_encoder.feature_dim * num_images
        if self.config.env_state_feature:
            global_cond_dim += self.config.env_state_feature.shape[0]

        base_global_cond_dim = global_cond_dim * config.n_obs_steps

        if config.use_critic:
            self.critic = DiffusionCritic(base_global_cond_dim, config.critic_hidden_dims)
            self.adv_embedding = nn.Embedding(2, config.adv_embed_dim)
            unet_cond_dim = base_global_cond_dim + config.adv_embed_dim
        else:
            unet_cond_dim = base_global_cond_dim

        if use_dit:
            state_dim = (
                self.config.robot_state_feature.shape[0] * config.n_obs_steps
                + (self.config.env_state_feature.shape[0] if self.config.env_state_feature else 0)
            )
            if config.use_critic:
                state_dim += config.adv_embed_dim
            self.unet = Gr00tDiTUnetWrapper(
                config,
                encoder_token_dim=self.rgb_encoder.feature_dim,
                state_dim=state_dim,
            )
        else:
            self.unet = DiffusionConditionalUnet1d(config, global_cond_dim=unet_cond_dim)

        self.noise_scheduler = _make_noise_scheduler(
            config.noise_scheduler_type,
            num_train_timesteps=config.num_train_timesteps,
            beta_start=config.beta_start,
            beta_end=config.beta_end,
            beta_schedule=config.beta_schedule,
            clip_sample=config.clip_sample,
            clip_sample_range=config.clip_sample_range,
            prediction_type=config.prediction_type,
        )

        if config.num_inference_steps is None:
            self.num_inference_steps = self.noise_scheduler.config.num_train_timesteps
        else:
            self.num_inference_steps = config.num_inference_steps

    # ========= inference  ============
    def conditional_sample(
        self,
        batch_size: int,
        global_cond: Tensor | None = None,
        generator: torch.Generator | None = None,
        noise: Tensor | None = None,
        action_cond=None,
        pretrained_unet=None,
        num_ft_train_steps: int = 0,
        noise_injection_std: float = 0.0,
    ) -> Tensor:
        """
        pretrained_unet: frozen pre-trained UNet used for t >= num_ft_train_steps
                         (high-noise coarse denoising steps). None = use self.unet throughout.
        num_ft_train_steps: timestep cutoff. Steps with t < num_ft_train_steps use self.unet
                            (fine-tuned); steps with t >= num_ft_train_steps use pretrained_unet.
        noise_injection_std: ignored for DDPM (noise is handled by the scheduler); used by FlowModel.
        """
        assert noise_injection_std == 0.0, "Noise injection is not supported for DiffusionPolicy"
        device = get_device_from_parameters(self)
        dtype = get_dtype_from_parameters(self)

        if action_cond is not None:
            raise NotImplementedError

        # Sample prior.
        sample = (
            noise
            if noise is not None
            else torch.randn(
                size=(batch_size, self.config.horizon, self.config.action_feature.shape[0]),
                dtype=dtype,
                device=device,
                generator=generator,
            )
        )

        self.noise_scheduler.set_timesteps(self.num_inference_steps)

        for t in self.noise_scheduler.timesteps:
            # Use frozen pretrained UNet for high-noise steps, fine-tuned UNet for refinement steps.
            unet = (
                pretrained_unet
                if pretrained_unet is not None and t >= num_ft_train_steps
                else self.unet
            )
            # Predict model output.
            model_output = unet(
                sample,
                torch.full(sample.shape[:1], t, dtype=torch.long, device=sample.device),
                global_cond=global_cond,
            )
            # Compute previous image: x_t -> x_t-1
            sample = self.noise_scheduler.step(model_output, t, sample, generator=generator).prev_sample

        return sample

    def _prepare_base_global_conditioning(self, batch: dict[str, Tensor]) -> Tensor:
        """Encode image features and concatenate them all together along with the state vector.

        Returns (B, base_global_cond_dim) without any advantage embedding.
        """
        batch_size, n_obs_steps = batch[OBS_STATE].shape[:2]
        global_cond_feats = [batch[OBS_STATE]]
        # Extract image features.
        if self.config.image_features:
            if self.config.use_dit:
                # Token encoder returns (B, 1+N, D); mean-pool over tokens for flat conditioning (e.g. critic).
                tokens = self.rgb_encoder(
                    einops.rearrange(batch[OBS_IMAGES], "b s n ... -> (b s n) ...")
                )
                img_features = tokens.mean(dim=1)
                img_features = einops.rearrange(
                    img_features, "(b s n) ... -> b s (n ...)", b=batch_size, s=n_obs_steps
                )
            elif self.config.use_separate_rgb_encoder_per_camera:
                # Combine batch and sequence dims while rearranging to make the camera index dimension first.
                images_per_camera = einops.rearrange(batch[OBS_IMAGES], "b s n ... -> n (b s) ...")

                if self.config.vision_backbone == "small_vit":
                    img_features_list = torch.cat([
                        encoder(images, batch[OBS_STATE])
                        for encoder, images in zip(self.rgb_encoder, images_per_camera, strict=True)
                    ])
                else:
                    img_features_list = torch.cat(
                        [
                            encoder(images)
                            for encoder, images in zip(self.rgb_encoder, images_per_camera, strict=True)
                        ]
                    )
                # Separate batch and sequence dims back out. The camera index dim gets absorbed into the
                # feature dim (effectively concatenating the camera features).
                img_features = einops.rearrange(
                    img_features_list, "(n b s) ... -> b s (n ...)", b=batch_size, s=n_obs_steps
                )
            else:
                # Combine batch, sequence, and "which camera" dims before passing to shared encoder.
                img_features = self.rgb_encoder(
                    einops.rearrange(batch[OBS_IMAGES], "b s n ... -> (b s n) ...")
                )
                # Separate batch dim and sequence dim back out. The camera index dim gets absorbed into the
                # feature dim (effectively concatenating the camera features).
                img_features = einops.rearrange(
                    img_features, "(b s n) ... -> b s (n ...)", b=batch_size, s=n_obs_steps
                )
            global_cond_feats.append(img_features)

        if self.config.env_state_feature:
            global_cond_feats.append(batch[OBS_ENV_STATE])

        # Concatenate features then flatten to (B, base_global_cond_dim).
        return torch.cat(global_cond_feats, dim=-1).flatten(start_dim=1)

    def _prepare_global_conditioning_dit(self, batch: dict[str, Tensor]) -> dict:
        """Prepare conditioning for DiT unet: encoder_tokens (B, N, D) and state (B, state_dim)."""
        batch_size, n_obs_steps = batch[OBS_STATE].shape[:2]
        num_cams = batch[OBS_IMAGES].shape[2]
        tokens = self.rgb_encoder(
            einops.rearrange(batch[OBS_IMAGES], "b s n ... -> (b s n) ...")
        )
        # obs step / cam id are not encoded
        tokens = einops.rearrange(
            tokens,
            "(b s n) t d -> b (s n t) d",
            b=batch_size,
            s=n_obs_steps,
            n=num_cams,
        )
        state_list = [batch[OBS_STATE]]
        if self.config.env_state_feature:
            state_list.append(batch[OBS_ENV_STATE])
        state = torch.cat(state_list, dim=-1).flatten(start_dim=1)
        if self.config.use_critic:
            if "adv_cond" in batch:
                adv_cond = batch["adv_cond"].long()
            else:
                adv_cond = torch.ones(batch_size, dtype=torch.long, device=state.device)
            state = torch.cat([state, self.adv_embedding(adv_cond)], dim=-1)
        return {"encoder_tokens": tokens, "state": state}

    def _prepare_global_conditioning(self, batch: dict[str, Tensor]) -> Tensor | dict:
        """Encode observations and optionally append advantage embedding for DPPO-style conditioning.
        When use_dit is True, returns a dict for the DiT wrapper; otherwise a flat tensor."""
        if self.config.use_dit:
            return self._prepare_global_conditioning_dit(batch)
        global_cond = self._prepare_base_global_conditioning(batch)  # (B, base_cond_dim)
        if self.config.use_critic:
            if "adv_cond" in batch:
                adv_cond = batch["adv_cond"].long()
            else:
                # Inference default: high advantage (adv_cond=1)
                adv_cond = torch.ones(global_cond.shape[0], dtype=torch.long, device=global_cond.device)
            adv_embed = self.adv_embedding(adv_cond)  # (B, adv_embed_dim)
            global_cond = torch.cat([global_cond, adv_embed], dim=-1)
        return global_cond

    def generate_actions(self, batch: dict[str, Tensor], noise: Tensor | None = None, full_length: bool = False, action_cond=None, noise_injection_std: float = 0.0) -> Tensor:
        """
        This function expects `batch` to have:
        {
            "observation.state": (B, n_obs_steps, state_dim)

            "observation.images": (B, n_obs_steps, num_cameras, C, H, W)
                AND/OR
            "observation.environment_state": (B, n_obs_steps, environment_dim)
        }
        """
        batch_size, n_obs_steps = batch[OBS_STATE].shape[:2]
        assert n_obs_steps == self.config.n_obs_steps

        # Encode image features and concatenate them all together along with the state vector.
        global_cond = self._prepare_global_conditioning(batch)  # (B, global_cond_dim)

        # run sampling
        actions = self.conditional_sample(batch_size, global_cond=global_cond, noise=noise, action_cond=action_cond, noise_injection_std=noise_injection_std)

        # Extract `n_action_steps` steps worth of actions (from the current observation).
        start = n_obs_steps - 1
        if full_length:
            actions = actions[:, start:]
        else:
            end = start + self.config.n_action_steps
            actions = actions[:, start:end]

        return actions

    def compute_loss(self, batch: dict[str, Tensor], max_timestep: int | None = None) -> Tensor:
        """
        This function expects `batch` to have (at least):
        {
            "observation.state": (B, n_obs_steps, state_dim)

            "observation.images": (B, n_obs_steps, num_cameras, C, H, W)
                AND/OR
            "observation.environment_state": (B, n_obs_steps, environment_dim)

            "action": (B, horizon, action_dim)
            "action_is_pad": (B, horizon)
        }

        max_timestep: if set, restrict training to DDPM timesteps [0, max_timestep).
            Used by PARL-BC to avoid training the fine-tuned UNet on timesteps handled
            by the frozen pretrained UNet at inference (t >= max_timestep).
        """
        # Input validation.
        assert set(batch).issuperset({OBS_STATE, ACTION, "action_is_pad"})
        assert OBS_IMAGES in batch or OBS_ENV_STATE in batch
        n_obs_steps = batch[OBS_STATE].shape[1]
        horizon = batch[ACTION].shape[1]
        assert horizon == self.config.horizon
        assert n_obs_steps == self.config.n_obs_steps

        # Encode image features and concatenate them all together along with the state vector.
        global_cond = self._prepare_global_conditioning(batch)  # (B, global_cond_dim)

        # Forward diffusion.
        trajectory = batch[ACTION]
        # Sample noise to add to the trajectory.
        eps = torch.randn(trajectory.shape, device=trajectory.device)
        # Sample a random noising timestep for each item in the batch.
        high = max_timestep if max_timestep is not None else self.noise_scheduler.config.num_train_timesteps
        timesteps = torch.randint(
            low=0,
            high=high,
            size=(trajectory.shape[0],),
            device=trajectory.device,
        ).long()
        # Add noise to the clean trajectories according to the noise magnitude at each timestep.
        noisy_trajectory = self.noise_scheduler.add_noise(trajectory, eps, timesteps)

        # Run the denoising network (that might denoise the trajectory, or attempt to predict the noise).
        pred = self.unet(noisy_trajectory, timesteps, global_cond=global_cond)

        # Compute the loss.
        # The target is either the original trajectory, or the noise.
        if self.config.prediction_type == "epsilon":
            target = eps
        elif self.config.prediction_type == "sample":
            target = batch[ACTION]
        else:
            raise ValueError(f"Unsupported prediction type {self.config.prediction_type}")

        loss = F.mse_loss(pred, target, reduction="none")

        # Mask loss wherever the action is padded with copies (edges of the dataset trajectory).
        if self.config.do_mask_loss_for_padding:
            if "action_is_pad" not in batch:
                raise ValueError(
                    "You need to provide 'action_is_pad' in the batch when "
                    f"{self.config.do_mask_loss_for_padding=}."
                )
            in_episode_bound = ~batch["action_is_pad"]
            loss = loss * in_episode_bound.unsqueeze(-1)

        return loss.mean()

    def critic_loss(self, batch: dict[str, Tensor]) -> Tensor:
        """MSE loss for value critic: V(obs) → return estimate."""
        global_cond = self._prepare_base_global_conditioning(batch)  # (B, base_cond_dim)
        values = self.critic(global_cond).squeeze(-1)  # (B,)
        return F.mse_loss(values, batch["ret"])


class FlowModel(DiffusionModel):
    def __init__(self, config: DiffusionConfig):
        super().__init__(config)

    def _legato_step(self, sample, global_cond, action_cond):
        conditioned_sample = (1-w) * sample + w * conditioned_sample
        vel = self.unet(conditioned_sample, taus, global_cond=global_cond).squeeze(0)
        return sample + vel / self.num_inference_steps


    def conditional_sample(
        self,
        batch_size: int,
        global_cond: Tensor | None = None,
        generator: torch.Generator | None = None,
        noise: Tensor | None = None,
        action_cond=None,
        pretrained_unet=None,
        num_ft_train_steps: int = 0,
        noise_injection_std: float = 0.0,
    ) -> Tensor:
        """
        pretrained_unet: frozen pre-trained UNet used for early (high-noise) flow steps.
                         None = use self.unet throughout.
        num_ft_train_steps: number of fine-tuned steps in DDPM convention. The last
                            num_ft_train_steps denoising steps (i >= num_inference_steps -
                            num_ft_train_steps, i.e. tau in [1 - num_ft_train_steps /
                            num_inference_steps, 1)) use self.unet; earlier steps use
                            pretrained_unet.
        """
        device = get_device_from_parameters(self)
        dtype = get_dtype_from_parameters(self)

        # Sample prior.
        sample = (
            noise
            if noise is not None
            else torch.randn(
                size=(batch_size, self.config.horizon, self.config.action_feature.shape[0]),
                dtype=dtype,
                device=device,
                generator=generator,
            )
        )

        self.noise_scheduler.set_timesteps(self.num_inference_steps)

        for i in range(self.num_inference_steps):
            # Flow matching: t in [0, 1). UNet expects continuous timestep (same as in compute_loss).
            tau = i / self.num_inference_steps
            taus = torch.full(sample.shape[:1], tau, dtype=dtype, device=sample.device)

            # Use frozen pretrained UNet for early (high-noise) steps, fine-tuned UNet for later steps.
            # Fine-tuned steps are the last num_ft_train_steps steps (DDPM convention), i.e. those
            # where i >= num_inference_steps - num_ft_train_steps.
            unet = (
                pretrained_unet
                if pretrained_unet is not None and i < (self.num_inference_steps - num_ft_train_steps)
                else self.unet
            )

            if action_cond is not None and self.config.rtc_type == 'inference_time_soft':
                assert batch_size == action_cond.shape[0] == 1, "Batch is not suported"
                # Preparations.
                single_action_cond = action_cond.squeeze(0)
                commit_step = len(single_action_cond)
                single_action_cond = torch.cat([
                    single_action_cond,
                    torch.zeros(self.config.horizon - len(single_action_cond), sample.shape[-1], device=single_action_cond.device)
                ])
                tau = np.array(tau)
                coeff = (1 - tau) / (
                    tau * (1 - tau) ** 2 / (
                        tau**2 + (1 - tau) ** 2
                    )
                )
                soft_interval = (self.config.rtc_delay, self.config.horizon - commit_step)
                a, b = soft_interval
                indices = torch.arange(self.config.horizon, device=sample.device)
                linear_c = (b - indices) / (b - a + 1)
                exp_c = linear_c * (torch.exp(linear_c) - 1) / (np.e - 1)

                single_inpaint_mask = exp_c
                single_inpaint_mask[:a] = 1
                single_inpaint_mask[b:] = 0

                # (Y-A1)^T diag(W)  X   dA_1 / dA_tau
                def single_a_1_fn(single_a_tau):
                    single_vel = unet(single_a_tau.unsqueeze(0), taus, global_cond=global_cond).squeeze(0)
                    single_a_1 = single_a_tau + (1 - tau) * single_vel
                    return single_a_1, single_vel
                single_a_tau = sample.squeeze(0)
                with torch.enable_grad():
                    single_a_1, vjp_fn, single_vel = torch.func.vjp(
                        single_a_1_fn, single_a_tau, has_aux=True
                    )
                    single_masked_error = (single_action_cond - single_a_1) * single_inpaint_mask[:, None]
                    single_guidance = vjp_fn(single_masked_error)[0]

                coeff = min(5, coeff)
                vel = (single_vel + coeff * single_guidance).unsqueeze(0)

            elif action_cond is not None and self.config.rtc_type == "train_time":
                B, H = sample.shape[:2]
                # Inpaint prefix before each model call, matching JAX sample_actions.
                sample[:, :self.config.rtc_delay] = action_cond[:, :self.config.rtc_delay]
                taus_per_step = taus.unsqueeze(1).expand(B, H).clone()  # (B, H)
                taus_per_step[:, :self.config.rtc_delay] = 1.0
                vel = unet(sample, taus_per_step, global_cond=global_cond)

            elif self.config.rtc_type == "legato":
                pass
            else:
                vel = unet(
                    sample,
                    taus,
                    global_cond=global_cond,
                )

            sample = sample + vel / self.num_inference_steps
            if noise_injection_std > 0.0:
                sample = sample + noise_injection_std * torch.randn_like(sample)

        if self.config.rtc_type == 'train_time' and action_cond is not None:
            sample[:, :self.config.rtc_delay] = action_cond[:, :self.config.rtc_delay]

        return sample

    def compute_loss(self, batch: dict[str, Tensor], max_timestep: int | None = None) -> Tensor:
        # Input validation.
        assert set(batch).issuperset({OBS_STATE, ACTION, "action_is_pad"})
        assert OBS_IMAGES in batch or OBS_ENV_STATE in batch
        n_obs_steps = batch[OBS_STATE].shape[1]
        horizon = batch[ACTION].shape[1]
        assert horizon == self.config.horizon
        assert n_obs_steps == self.config.n_obs_steps

        # Encode image features and concatenate them all together along with the state vector.
        global_cond = self._prepare_global_conditioning(batch)  # (B, global_cond_dim)
# Forward diffusion.
        trajectory = batch[ACTION]
        # Sample noise to add to the trajectory.
        eps = torch.randn(trajectory.shape, device=trajectory.device)

        B = trajectory.shape[0]
        H = trajectory.shape[1]
        device = trajectory.device

        # max_timestep is in DDPM step convention [0, K).
        # For flow matching, fine-tuned steps are the last max_timestep denoising steps,
        # corresponding to tau in [1 - max_timestep/num_inference_steps, 1).
        tau_min = (
            1.0 - max_timestep / self.num_inference_steps
            if max_timestep is not None else 0.0
        )

        if self.config.t_schedule is None:
            timesteps = tau_min + torch.rand(B, device=device) * (1.0 - tau_min)
            timesteps = timesteps[:, None].expand(B, H).clone()  # (B, H)
        elif self.config.t_schedule == 'beta0.999':
            z = torch.distributions.Beta(1.5, 1).sample((B,)).to(device)
            t = 0.999 * (1 - z)  # t in [0, 0.999]
            # Rescale [0, 0.999] -> [tau_min, 1) to restrict to fine-tuned tau range.
            t = tau_min + t * (1.0 - tau_min) / 0.999
            timesteps = t[:, None].expand(B, H).clone()  # (B, H)

        noisy_trajectory = (1 - timesteps.unsqueeze(-1)) * eps + timesteps.unsqueeze(-1) * trajectory

        vel = trajectory - eps

        if self.config.rtc_type == "train_time":
            d = torch.randint(0, self.config.rtc_delay, (B,), device=device)
            # mask[b, h] = True if h < d[b], shape (B, H)
            h_idx = torch.arange(H, device=device).unsqueeze(0)
            mask = h_idx < d.unsqueeze(1)  # (B, H)
            max_t = 1.0 if self.config.t_schedule is None else 0.999
            timesteps = timesteps.masked_fill(mask, max_t)
            noisy_trajectory = torch.where(mask.unsqueeze(-1).expand_as(trajectory), trajectory, noisy_trajectory)

        pred = self.unet(noisy_trajectory, timesteps, global_cond=global_cond)

        if self.config.rtc_type == "train_time":
            # Loss only on non-fixed steps; normalize by unmasked count to preserve scale.
            loss_elem = F.mse_loss(pred, vel, reduction='none')  # (B, H, action_dim)
            unmasked = (~mask).unsqueeze(-1).expand_as(loss_elem)
            loss = loss_elem[unmasked].mean() * (B * H) / (~mask).sum()
        else:
            loss = F.mse_loss(pred, vel)

        if self.config.do_mask_loss_for_padding:
            raise NotImplementedError("Mask loss for padding is not implemented for flow model")

        return loss


class SpatialSoftmax(nn.Module):
    """
    Spatial Soft Argmax operation described in "Deep Spatial Autoencoders for Visuomotor Learning" by Finn et al.
    (https://huggingface.co/papers/1509.06113). A minimal port of the robomimic implementation.

    At a high level, this takes 2D feature maps (from a convnet/ViT) and returns the "center of mass"
    of activations of each channel, i.e., keypoints in the image space for the policy to focus on.

    Example: take feature maps of size (512x10x12). We generate a grid of normalized coordinates (10x12x2):
    -----------------------------------------------------
    | (-1., -1.)   | (-0.82, -1.)   | ... | (1., -1.)   |
    | (-1., -0.78) | (-0.82, -0.78) | ... | (1., -0.78) |
    | ...          | ...            | ... | ...         |
    | (-1., 1.)    | (-0.82, 1.)    | ... | (1., 1.)    |
    -----------------------------------------------------
    This is achieved by applying channel-wise softmax over the activations (512x120) and computing the dot
    product with the coordinates (120x2) to get expected points of maximal activation (512x2).

    The example above results in 512 keypoints (corresponding to the 512 input channels). We can optionally
    provide num_kp != None to control the number of keypoints. This is achieved by a first applying a learnable
    linear mapping (in_channels, H, W) -> (num_kp, H, W).
    """

    def __init__(self, input_shape, num_kp=None):
        """
        Args:
            input_shape (list): (C, H, W) input feature map shape.
            num_kp (int): number of keypoints in output. If None, output will have the same number of channels as input.
        """
        super().__init__()

        assert len(input_shape) == 3
        self._in_c, self._in_h, self._in_w = input_shape

        if num_kp is not None:
            self.nets = torch.nn.Conv2d(self._in_c, num_kp, kernel_size=1)
            self._out_c = num_kp
        else:
            self.nets = None
            self._out_c = self._in_c

        # we could use torch.linspace directly but that seems to behave slightly differently than numpy
        # and causes a small degradation in pc_success of pre-trained models.
        pos_x, pos_y = np.meshgrid(np.linspace(-1.0, 1.0, self._in_w), np.linspace(-1.0, 1.0, self._in_h))
        pos_x = torch.from_numpy(pos_x.reshape(self._in_h * self._in_w, 1)).float()
        pos_y = torch.from_numpy(pos_y.reshape(self._in_h * self._in_w, 1)).float()
        # register as buffer so it's moved to the correct device.
        self.register_buffer("pos_grid", torch.cat([pos_x, pos_y], dim=1))

    def forward(self, features: Tensor) -> Tensor:
        """
        Args:
            features: (B, C, H, W) input feature maps.
        Returns:
            (B, K, 2) image-space coordinates of keypoints.
        """
        if self.nets is not None:
            features = self.nets(features)

        # [B, K, H, W] -> [B * K, H * W] where K is number of keypoints
        features = features.reshape(-1, self._in_h * self._in_w)
        # 2d softmax normalization
        attention = F.softmax(features, dim=-1)
        # [B * K, H * W] x [H * W, 2] -> [B * K, 2] for spatial coordinate mean in x and y dimensions
        expected_xy = attention @ self.pos_grid
        # reshape to [B, K, 2]
        feature_keypoints = expected_xy.view(-1, self._out_c, 2)

        return feature_keypoints


class DiffusionSmallVitEncoder(nn.Module):
    """Single image-view ViT encoder for diffusion: 96x96 resize + VitEncoder (speedaug), one per camera."""

    IMG_SIZE = 96

    def __init__(self, config: DiffusionConfig) -> None:
        super().__init__()
        from speedaug.models.common.vit import VitEncoder, VitEncoderConfig
        from speedaug.models.common.modules import SpatialEmb

        self.backbone = VitEncoder(
            VitEncoderConfig(
                patch_size=8,
                depth=1,
                embed_dim=64,
                num_heads=4,
                embed_style="embed2",
                embed_norm=0,
            ),
            num_channel=3,
            img_h=self.IMG_SIZE,
            img_w=self.IMG_SIZE,
            n_img=1,
        )
        self.compress = SpatialEmb(
            num_patch=self.backbone.num_patch,
            patch_dim=self.backbone.patch_repr_dim,
            prop_dim=config.robot_state_feature.shape[0],
            proj_dim=64,
            dropout=0,
        )
        self.feature_dim = 64
        self.resize = torchvision.transforms.Resize((self.IMG_SIZE, self.IMG_SIZE))

    def forward(self, x: Tensor, state: Tensor) -> Tensor:
        if x.shape[-2:] != (self.IMG_SIZE, self.IMG_SIZE):
            x = self.resize(x)
        x = self.backbone(x, scale=False)
        x = self.compress(x, state.flatten(1, 2))
        return x


class DiffusionDinoV3Encoder(nn.Module):
    """Encodes an RGB image using DINOv3 loaded via torch.hub (local repo).
    When return_patch_tokens is True (e.g. for DiT), returns (B, N_patches, embed_dim) from x_norm_patchtokens.
    Otherwise returns (B, feature_dim) CLS token.
    """

    IMG_SIZE = 256
    IMAGENET_MEAN = (0.485, 0.456, 0.406)
    IMAGENET_STD = (0.229, 0.224, 0.225)

    def __init__(self, config: DiffusionConfig):
        super().__init__()
        repo_dir = getattr(config, "dinov3_hub_repo", None)
        if not repo_dir:
            raise ValueError(
                "DiffusionDinoV3Encoder requires config.dinov3_hub_repo (path to local dinov3 repo)."
            )
        entrypoint = config.vision_backbone  # e.g. "dinov3_vits16plus"
        weights_path = getattr(config, "dinov3_hub_weights", None)
        hub_kwargs = {"source": "local", "pretrained": True}
        if weights_path:
            hub_kwargs["weights"] = weights_path
        self.backbone = torch.hub.load(repo_dir, entrypoint, **hub_kwargs)
        self.feature_dim = self.backbone.embed_dim
        self.resize = torchvision.transforms.Resize((self.IMG_SIZE, self.IMG_SIZE))
        self._config = config
        self.return_patch_tokens = config.use_dit

    def forward(self, x: Tensor) -> Tensor:
        """
        Args:
            x: (B, C, H, W) image tensor with pixel values in [0, 1].
        Returns:
            (B, feature_dim) CLS token, or (B, N_patches, feature_dim) patch tokens when return_patch_tokens.
        """
        if x.shape[-2:] != (self.IMG_SIZE, self.IMG_SIZE):
            x = self.resize(x)
        mean = torch.tensor(self.IMAGENET_MEAN, device=x.device, dtype=x.dtype).view(1, 3, 1, 1)
        std = torch.tensor(self.IMAGENET_STD, device=x.device, dtype=x.dtype).view(1, 3, 1, 1)
        x = (x - mean) / std

        if self.return_patch_tokens:
            out = self.backbone.forward_features(x)
            out = out['x_norm_patchtokens']
        else:
            out = self.backbone(x)
        return out


class DiffusionRgbEncoder(nn.Module):
    """Encodes an RGB image into a 1D feature vector.

    Includes the ability to normalize and crop the image first.
    """

    def __init__(self, config: DiffusionConfig):
        super().__init__()
        # Set up optional preprocessing.
        if config.crop_shape is not None:
            self.do_crop = True
            # Always use center crop for eval
            self.center_crop = torchvision.transforms.CenterCrop(config.crop_shape)
            if config.crop_is_random:
                self.maybe_random_crop = torchvision.transforms.RandomCrop(config.crop_shape)
            else:
                self.maybe_random_crop = self.center_crop
        else:
            self.do_crop = False

        # Set up backbone.
        backbone_model = getattr(torchvision.models, config.vision_backbone)(
            weights=config.pretrained_backbone_weights
        )
        # Note: This assumes that the layer4 feature map is children()[-3]
        # TODO(alexander-soare): Use a safer alternative.
        self.backbone = nn.Sequential(*(list(backbone_model.children())[:-2]))
        if config.use_group_norm:
            if config.pretrained_backbone_weights:
                raise ValueError(
                    "You can't replace BatchNorm in a pretrained model without ruining the weights!"
                )
            self.backbone = _replace_submodules(
                root_module=self.backbone,
                predicate=lambda x: isinstance(x, nn.BatchNorm2d),
                func=lambda x: nn.GroupNorm(num_groups=x.num_features // 16, num_channels=x.num_features),
            )

        # Set up pooling and final layers.
        # Use a dry run to get the feature map shape.
        # The dummy input should take the number of image channels from `config.image_features` and it should
        # use the height and width from `config.crop_shape` if it is provided, otherwise it should use the
        # height and width from `config.image_features`.

        # Note: we have a check in the config class to make sure all images have the same shape.
        images_shape = next(iter(config.image_features.values())).shape
        dummy_shape_h_w = config.crop_shape if config.crop_shape is not None else images_shape[1:]
        dummy_shape = (1, images_shape[0], *dummy_shape_h_w)
        feature_map_shape = get_output_shape(self.backbone, dummy_shape)[1:]

        self.pool = SpatialSoftmax(feature_map_shape, num_kp=config.spatial_softmax_num_keypoints)
        self.feature_dim = config.spatial_softmax_num_keypoints * 2
        self.out = nn.Linear(config.spatial_softmax_num_keypoints * 2, self.feature_dim)
        self.relu = nn.ReLU()

    def forward(self, x: Tensor) -> Tensor:
        """
        Args:
            x: (B, C, H, W) image tensor with pixel values in [0, 1].
        Returns:
            (B, D) image feature.
        """
        # Preprocess: maybe crop (if it was set up in the __init__).
        if self.do_crop:
            if self.training:  # noqa: SIM108
                x = self.maybe_random_crop(x)
            else:
                # Always use center crop for eval.
                x = self.center_crop(x)
        # Extract backbone feature.
        x = torch.flatten(self.pool(self.backbone(x)), start_dim=1)
        # Final linear layer with non-linearity.
        x = self.relu(self.out(x))
        return x


def _replace_submodules(
    root_module: nn.Module, predicate: Callable[[nn.Module], bool], func: Callable[[nn.Module], nn.Module]
) -> nn.Module:
    """
    Args:
        root_module: The module for which the submodules need to be replaced
        predicate: Takes a module as an argument and must return True if the that module is to be replaced.
        func: Takes a module as an argument and returns a new module to replace it with.
    Returns:
        The root module with its submodules replaced.
    """
    if predicate(root_module):
        return func(root_module)

    replace_list = [k.split(".") for k, m in root_module.named_modules(remove_duplicate=True) if predicate(m)]
    for *parents, k in replace_list:
        parent_module = root_module
        if len(parents) > 0:
            parent_module = root_module.get_submodule(".".join(parents))
        if isinstance(parent_module, nn.Sequential):
            src_module = parent_module[int(k)]
        else:
            src_module = getattr(parent_module, k)
        tgt_module = func(src_module)
        if isinstance(parent_module, nn.Sequential):
            parent_module[int(k)] = tgt_module
        else:
            setattr(parent_module, k, tgt_module)
    # verify that all BN are replaced
    assert not any(predicate(m) for _, m in root_module.named_modules(remove_duplicate=True))
    return root_module


class DiffusionSinusoidalPosEmb(nn.Module):
    """1D sinusoidal positional embeddings as in Attention is All You Need."""

    def __init__(self, dim: int):
        super().__init__()
        self.dim = dim

    def forward(self, x: Tensor) -> Tensor:
        device = x.device
        half_dim = self.dim // 2
        emb = math.log(10000) / (half_dim - 1)
        emb = torch.exp(torch.arange(half_dim, device=device) * -emb)
        emb = x.unsqueeze(-1) * emb.unsqueeze(0)
        emb = torch.cat((emb.sin(), emb.cos()), dim=-1)
        return emb


class DiffusionConv1dBlock(nn.Module):
    """Conv1d --> GroupNorm --> Mish"""

    def __init__(self, inp_channels, out_channels, kernel_size, n_groups=8):
        super().__init__()

        self.block = nn.Sequential(
            nn.Conv1d(inp_channels, out_channels, kernel_size, padding=kernel_size // 2),
            nn.GroupNorm(n_groups, out_channels),
            nn.Mish(),
        )

    def forward(self, x):
        return self.block(x)


class DiffusionConditionalUnet1d(nn.Module):
    """A 1D convolutional UNet with FiLM modulation for conditioning.

    Note: this removes local conditioning as compared to the original diffusion policy code.
    """

    def __init__(self, config: DiffusionConfig, global_cond_dim: int):
        super().__init__()

        self.config = config

        # Encoder for the diffusion timestep.
        self.diffusion_step_encoder = nn.Sequential(
            DiffusionSinusoidalPosEmb(config.diffusion_step_embed_dim),
            nn.Linear(config.diffusion_step_embed_dim, config.diffusion_step_embed_dim * 4),
            nn.Mish(),
            nn.Linear(config.diffusion_step_embed_dim * 4, config.diffusion_step_embed_dim),
        )

        # The FiLM conditioning dimension.
        cond_dim = config.diffusion_step_embed_dim + global_cond_dim

        # In channels / out channels for each downsampling block in the Unet's encoder. For the decoder, we
        # just reverse these.
        in_out = [(config.action_feature.shape[0], config.down_dims[0])] + list(
            zip(config.down_dims[:-1], config.down_dims[1:], strict=True)
        )

        # Unet encoder.
        common_res_block_kwargs = {
            "cond_dim": cond_dim,
            "kernel_size": config.kernel_size,
            "n_groups": config.n_groups,
            "use_film_scale_modulation": config.use_film_scale_modulation,
        }
        self.down_modules = nn.ModuleList([])
        for ind, (dim_in, dim_out) in enumerate(in_out):
            is_last = ind >= (len(in_out) - 1)
            self.down_modules.append(
                nn.ModuleList(
                    [
                        DiffusionConditionalResidualBlock1d(dim_in, dim_out, **common_res_block_kwargs),
                        DiffusionConditionalResidualBlock1d(dim_out, dim_out, **common_res_block_kwargs),
                        # Downsample as long as it is not the last block.
                        nn.Conv1d(dim_out, dim_out, 3, 2, 1) if not is_last else nn.Identity(),
                    ]
                )
            )

        # Processing in the middle of the auto-encoder.
        self.mid_modules = nn.ModuleList(
            [
                DiffusionConditionalResidualBlock1d(
                    config.down_dims[-1], config.down_dims[-1], **common_res_block_kwargs
                ),
                DiffusionConditionalResidualBlock1d(
                    config.down_dims[-1], config.down_dims[-1], **common_res_block_kwargs
                ),
            ]
        )

        # Unet decoder.
        self.up_modules = nn.ModuleList([])
        for ind, (dim_out, dim_in) in enumerate(reversed(in_out[1:])):
            is_last = ind >= (len(in_out) - 1)
            self.up_modules.append(
                nn.ModuleList(
                    [
                        # dim_in * 2, because it takes the encoder's skip connection as well
                        DiffusionConditionalResidualBlock1d(dim_in * 2, dim_out, **common_res_block_kwargs),
                        DiffusionConditionalResidualBlock1d(dim_out, dim_out, **common_res_block_kwargs),
                        # Upsample as long as it is not the last block.
                        nn.ConvTranspose1d(dim_out, dim_out, 4, 2, 1) if not is_last else nn.Identity(),
                    ]
                )
            )

        self.final_conv = nn.Sequential(
            DiffusionConv1dBlock(config.down_dims[0], config.down_dims[0], kernel_size=config.kernel_size),
            nn.Conv1d(config.down_dims[0], config.action_feature.shape[0], 1),
        )

    def forward(self, x: Tensor, timestep: Tensor | int, global_cond=None) -> Tensor:
        """
        Args:
            x: (B, T, input_dim) tensor for input to the Unet.
            timestep: (B,) tensor of (timestep_we_are_denoising_from - 1).
            global_cond: (B, global_cond_dim)
            output: (B, T, input_dim)
        Returns:
            (B, T, input_dim) diffusion model prediction.
        """
        # For 1D convolutions we'll need feature dimension first.
        x = einops.rearrange(x, "b t d -> b d t")

        timesteps_embed = self.diffusion_step_encoder(timestep)

        # If there is a global conditioning feature, concatenate it to the timestep embedding.
        if global_cond is not None:
            global_feature = torch.cat([timesteps_embed, global_cond], axis=-1)
        else:
            global_feature = timesteps_embed

        # Run encoder, keeping track of skip features to pass to the decoder.
        encoder_skip_features: list[Tensor] = []
        for resnet, resnet2, downsample in self.down_modules:
            x = resnet(x, global_feature)
            x = resnet2(x, global_feature)
            encoder_skip_features.append(x)
            x = downsample(x)

        for mid_module in self.mid_modules:
            x = mid_module(x, global_feature)

        # Run decoder, using the skip features from the encoder.
        for resnet, resnet2, upsample in self.up_modules:
            x = torch.cat((x, encoder_skip_features.pop()), dim=1)
            x = resnet(x, global_feature)
            x = resnet2(x, global_feature)
            x = upsample(x)

        x = self.final_conv(x)

        x = einops.rearrange(x, "b d t -> b t d")
        return x


class Gr00tDiTUnetWrapper(nn.Module):
    """GR00T-style DiT as drop-in for self.unet: forward(x, timestep, global_cond) -> (B, T, action_dim).
    State and action are encoded, stacked as DiT input; encoder_tokens (vision) are encoder_hidden_states.
    - State encoder: 2-layer MLP (s -> h -> h).
    - Action encoder: 2-layer MLP (T, a) -> (T, h) -> (T, h) with action position embeddings.
    - Action decoder: 2-layer MLP (h -> h -> a) on DiT output action tokens.
    """

    def __init__(self, config: DiffusionConfig, encoder_token_dim: int, state_dim: int):
        super().__init__()
        try:
            from gr00t.model.modules.dit import DiT
        except ImportError as e:
            raise ImportError("Gr00tDiTUnetWrapper requires gr00t. Use diffusion_type='diffusion'.") from e
        self.config = config
        action_dim = config.action_feature.shape[0]
        horizon = config.horizon
        embedding_hidden_dim = config.dit_embedding_hidden_dim
        dit_hidden_dim = config.dit_num_attention_heads * config.dit_attention_head_dim
        cross_dim = encoder_token_dim

        # State encoder: 2-layer MLP (s -> h -> h)
        self.state_encoder = nn.Sequential(
            nn.Linear(state_dim, embedding_hidden_dim),
            nn.ReLU(inplace=True),
            nn.Linear(embedding_hidden_dim, dit_hidden_dim),
        )

        # Action encoder: 2 layers (T, a) -> (T, h) -> (T, h)
        self.action_encoder = nn.Sequential(
            nn.Linear(action_dim, embedding_hidden_dim),
            nn.ReLU(inplace=True),
            nn.Linear(embedding_hidden_dim, dit_hidden_dim),
        )

        # Action position embeddings (for the T action tokens)
        self.action_position_embedding = nn.Embedding(horizon, dit_hidden_dim)
        nn.init.normal_(self.action_position_embedding.weight, mean=0.0, std=0.02)

        self.dit = DiT(
            num_attention_heads=config.dit_num_attention_heads,
            attention_head_dim=config.dit_attention_head_dim,
            output_dim=embedding_hidden_dim,
            num_layers=config.dit_num_layers,
            dropout=config.dit_dropout,
            norm_type=config.dit_norm_type,
            interleave_self_attention=config.dit_interleave_self_attention,
            cross_attention_dim=cross_dim,
        )

        # Action decoder: 2-layer MLP (h -> h -> a)
        self.action_decoder = nn.Sequential(
            nn.Linear(embedding_hidden_dim, embedding_hidden_dim),
            nn.ReLU(inplace=True),
            nn.Linear(embedding_hidden_dim, action_dim),
        )

    def forward(self, x: Tensor, timestep: Tensor | int, global_cond=None) -> Tensor:
        if not isinstance(global_cond, dict) or "encoder_tokens" not in global_cond or "state" not in global_cond:
            raise ValueError("Gr00tDiTUnetWrapper expects global_cond dict with 'encoder_tokens' and 'state'.")
        encoder_tokens = global_cond["encoder_tokens"]
        state = global_cond["state"]
        B, T, _ = x.shape

        if isinstance(timestep, int):
            timestep = torch.full((B,), timestep, device=x.device, dtype=torch.float32)
        if timestep.dim() == 2:
            # (B, H) per-step timesteps: prepend the last step's timestep for the state token.
            # The last action step is never in the inpainting region, so it always holds the base t.
            timestep = torch.cat([timestep[:, -1:], timestep], dim=1)  # (B, 1+H)

        state_embed = self.state_encoder(state).unsqueeze(1)
        action_embed = self.action_encoder(x)
        pos_ids = torch.arange(T, dtype=torch.long, device=x.device)
        action_embed = action_embed + self.action_position_embedding(pos_ids).unsqueeze(0)
        hidden_states = torch.cat([state_embed, action_embed], dim=1)

        out = self.dit(
            hidden_states,
            encoder_hidden_states=encoder_tokens,
            timestep=timestep,
        )
        action_tokens = out[:, 1:, :]
        return self.action_decoder(action_tokens)


class DiffusionConditionalResidualBlock1d(nn.Module):
    """ResNet style 1D convolutional block with FiLM modulation for conditioning."""

    def __init__(
        self,
        in_channels: int,
        out_channels: int,
        cond_dim: int,
        kernel_size: int = 3,
        n_groups: int = 8,
        # Set to True to do scale modulation with FiLM as well as bias modulation (defaults to False meaning
        # FiLM just modulates bias).
        use_film_scale_modulation: bool = False,
    ):
        super().__init__()

        self.use_film_scale_modulation = use_film_scale_modulation
        self.out_channels = out_channels

        self.conv1 = DiffusionConv1dBlock(in_channels, out_channels, kernel_size, n_groups=n_groups)

        # FiLM modulation (https://huggingface.co/papers/1709.07871) outputs per-channel bias and (maybe) scale.
        cond_channels = out_channels * 2 if use_film_scale_modulation else out_channels
        self.cond_encoder = nn.Sequential(nn.Mish(), nn.Linear(cond_dim, cond_channels))

        self.conv2 = DiffusionConv1dBlock(out_channels, out_channels, kernel_size, n_groups=n_groups)

        # A final convolution for dimension matching the residual (if needed).
        self.residual_conv = (
            nn.Conv1d(in_channels, out_channels, 1) if in_channels != out_channels else nn.Identity()
        )

    def forward(self, x: Tensor, cond: Tensor) -> Tensor:
        """
        Args:
            x: (B, in_channels, T)
            cond: (B, cond_dim)
        Returns:
            (B, out_channels, T)
        """
        out = self.conv1(x)

        # Get condition embedding. Unsqueeze for broadcasting to `out`, resulting in (B, out_channels, 1).
        cond_embed = self.cond_encoder(cond).unsqueeze(-1)
        if self.use_film_scale_modulation:
            # Treat the embedding as a list of scales and biases.
            scale = cond_embed[:, : self.out_channels]
            bias = cond_embed[:, self.out_channels :]
            out = scale * out + bias
        else:
            # Treat the embedding as biases.
            out = out + cond_embed

        out = self.conv2(out)
        out = out + self.residual_conv(x)
        return out
